sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t bluehave/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true bluehave/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: docker-react-app
  env: DockerReactApp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-125861765260
  bucket_path: docker-react-app
  on:
    branch: master

after_success:
  - echo "Test Success"